import requests
import pandas as pd
from sqlalchemy import create_engine
import psycopg2


drop_table = """ DROP TABLE IF EXISTS FACT_TABLE;"""
create_data_table = """CREATE TABLE FACT_TABLE (
        id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
        product_id VARCHAR(20), -- REFERENCES DIMBOOK(product_id), 
        category_id INT, -- REFERENCES DIMCATEGORY(category_id),
        sku VARCHAR(50),
        quantity_sold INT,
        price REAL,
        original_price REAL,
        discount REAL,
        discount_rate REAL,
        PRIMARY KEY(id)
    );"""
insert_data_toTable = """INSERT INTO product_data values(DEFAULT,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) ;"""


def main():
    conn = psycopg2.connect(
        database="airflow",
        user="hoangson",
        password="11111",
        host="localhost",
        port="5432",
    )
    cur = conn.cursor()
    cur.execute(drop_table)
    cur.execute(create_data_table)

    conn.commit()
    conn.close()
    cur.close()


if __name__ == "__main__":
    main()
